// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mysoft.Demo.Web.Models.DBConfig;

namespace Mysoft.Demo.Web.Migrations
{
    [DbContext(typeof(DemoContext))]
    [Migration("20181207072133_更新材料表结构")]
    partial class 更新材料表结构
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Mysoft.Demo.Web.Models.Product", b =>
                {
                    b.Property<Guid>("ProductGUID")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("CurrentPrice");

                    b.Property<string>("Description");

                    b.Property<string>("Pictures")
                        .HasMaxLength(800);

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("ProviderName")
                        .HasMaxLength(80);

                    b.Property<string>("Remark");

                    b.Property<string>("Unit")
                        .HasMaxLength(10);

                    b.HasKey("ProductGUID");

                    b.ToTable("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
