// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mysoft.Demo.Web.Models.DBConfig;

namespace Mysoft.Demo.Web.Migrations
{
    [DbContext(typeof(DemoContext))]
    partial class DemoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Mysoft.Demo.Web.Models.Product", b =>
                {
                    b.Property<Guid>("ProductGUID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Remark");

                    b.HasKey("ProductGUID");

                    b.ToTable("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
